ajout action pour lancer l'app avant de lancer le test robot framework

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -89,7 +89,7 @@ jobs:
       #   uses: joonvena/robotframework-docker-action@v1.1
       #   with:
       #     robot_tests_dir: app/test/system
-      - name: install dependencies
+      - name: install flask dependencies
         run: |
           python -m pip install --upgrade pip
           pip install flask
@@ -98,13 +98,21 @@ jobs:
         run: |
           flask --app=./app/main.py run --host=0.0.0.0 &
           sleep 5
-      - name: Install dependencies
+      - name: Test Application Availability
+        run: |
+          response=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:5000)
+          if [ $response -ne 200 ]; then
+            echo "Error: Application is not accessible. HTTP status code: $response"
+            exit 1
+          else
+            echo "Application is accessible!"
+          fi
+      - name: Install robot dependencies
         run: |
           python -m pip install --upgrade pip
           pip install robotframework
           pip install robotframework-requests
           pip install robotframework-browser
-          pip install flask
       - name: Analysing the code with robotframework
         run: |
           robot app/test/system/machine.robot
